//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.1
//     Last generated on 3/1/2018 3:53:30 PM by user svarney
//
//     Type: CTX
//     Transaction ID: S84_WEBADVISOR_URT
//     Application: CORE
//     Environment: CollTest01
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Student.Transactions.Custom
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.1")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "S84_WEBADVISOR_URT", GeneratedDateTime = "3/1/2018 3:53:30 PM", User = "svarney")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 1)]
	public class URTRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "PERSON.ID", InBoundData = true)]        
		public string ColleagueId { get; set; }

		public URTRequest()
		{	
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.1")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "S84_WEBADVISOR_URT", GeneratedDateTime = "3/1/2018 3:53:30 PM", User = "svarney")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 1)]
	public class URTResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "WEBADVISOR.USERNAME", OutBoundData = true)]        
		public string WebAdvisorId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "DATE.CREATED", OutBoundData = true)]        
		public string DateCreated { get; set; }

		public URTResponse()
		{	
		}
	}
}
